---
title: "Analysis"
author: "TawsifKhan"
date: "October 26, 2015"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---

```{r echo=FALSE}
library(ggplot2)
df = read.table("./output/wordcount.csv",
                sep = ",",
                na.strings = "N/A",
                col.names = c("Word","Location","Count"),
                header = FALSE
)
df = df[order(-df[,3]),]
```

```{r}
summary(df)
```
```{r echo=FALSE}
total_byLocation = aggregate(df$Count,
                            by = list(Location = df$Location),
                            FUN = "sum")
total_byLocation=total_byLocation[order(-total_byLocation[,2]),]

total_byWord = aggregate(df$Count,
                         by = list(Word = df$Word),
                         FUN = "sum")
total_byWord=total_byWord[order(-total_byWord[,2]),]

top_ten_word= total_byWord[1:10,]
top_ten_location = total_byLocation[2:10,]
``` 
```{r}
top_ten_location
```
```{r}
p1 <- ggplot(data=top_ten_location,aes(x=Location,y=x))
p1 <- p1 + geom_bar(stat="identity",size=1) + ylab("Frequency")
p1 <- p1 + theme_minimal()
p1
```
